[tool.pytest.ini_options]
addopts = "--verbose --html=reports/report.html --self-contained-html --css=resources/css/custom.css"

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 120
count = true
EXCLUDE = [".git", "__pycache__", "build", "dist", "venv", "docs"]
extend-ignore  = ["E203","E501","W503"]
#select = ["B", "C", "E", "F", "W"]
#extend-ignore = ["E203", "E501", "W503"]

[tool.ruff]
ignore = ["E501"]

[tool.bandit]
skips = [
    "B405",
    "B314",
    "B101",
    "B105",
    "B301",
    "B303",
    "B306",
    "B307",
    "B311",
    "B320",
    "B321",
    "B324",
    "B402",
    "B403",
    "B404",
    "B406",
    "B410",
    "B503",
    "B603",
    "B605"]
exclude_dirs = ["tests","venv"]
