apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "locust.fullname" . }}-{{ .Release.Name }}-master
  labels:
    component: master
    {{- include "locust.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      component: master
      {{- include "locust.selectorLabels" . | nindent 6 }}
  replicas: 1
  {{- with .Values.master.strategy }}
  strategy:
    {{ toYaml . | indent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        component: master
        {{- include "locust.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.pullSecretName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ if .Values.master.image }}{{ .Values.master.image }}{{ else }}{{ .Values.image.repository }}:{{ .Values.image.tag }}{{ end }}"
          {{- with .Values.master.command }}
          command:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - --master
            {{- if .Values.master.args }}
            {{- toYaml .Values.master.args | nindent 12 }}
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.master.resources | nindent 12 }}
          ports:
            - containerPort: 8089
              name: loc-master-web
              protocol: TCP
            - containerPort: 5557
              name: loc-master-p1
              protocol: TCP
            - containerPort: 5558
              name: loc-master-p2
              protocol: TCP
      restartPolicy: {{ .Values.master.restartPolicy }}
