{{- if .Values.global.env_secret }}
apiVersion: apps/v1
kind: Secret
metadata:
  name: {{ .Values.global.sub_url_secret }}
  labels:
{{ include "locust.labels" . | indent 4 }}
type: Opaque
stringData:
  x-api-key: {{ .Values.global.env_secret }}
{{- end }}
