---
{{- if .Values.global.env_secret }}
apiVersion: v1
kind: Secret
metadata:
#  name: {{ .Values.global.secret_name_api_key_locust }}
  name: {{ .Values.global.sub_url_secret }}
  labels:
{{ include "locust.labels" . | indent 4 }}
type: Opaque
stringData:
  x-api-key: {{ .Values.global.env_secret }}
{{- end }}
