apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "locust.fullname" . }}-{{ .Release.Name }}-worker
  labels:
    component: worker
    {{ include "locust.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      component: worker
      {{- include "locust.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.worker.replicas }}
  {{- with .Values.worker.strategy }}
  strategy:
    {{ toYaml . | indent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        component: worker
        {{- include "locust.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.pullSecretName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ if .Values.worker.image }}{{ .Values.worker.image }}{{ else }}{{ .Values.image.repository }}:{{ .Values.image.tag }}{{ end }}"
          {{- with .Values.worker.command }}
          command:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - --worker
            {{- if .Values.worker.args }}
            {{- toYaml .Values.worker.args | nindent 12 }}
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          ports:
            - containerPort: 8089
              name: loc-worker-web
              protocol: TCP
      restartPolicy: {{ .Values.worker.restartPolicy }}
