---
global:
  name: locust-global
  locust_file: wmts.py
  locust_file_path: "/mnt/locust/tests"
  locust_host: https://www.google.com
  env: {
      measure_time: false,
      pro_active_wmts_bbox: [35.024411528661574, 32.79419004139809, 35.37597717328861, 32.947998391903226],
      mc_region_value: "ישראל, ירדן",
      mc_polygon_value: '{"bbox":[34.8468438649828,32.0466327470143,34.8804418550117,32.0689996810298],"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[34.8468438649828,32.0689996810298],[34.8637856279928,32.0590059440186],[34.8773961450173,32.0680478960404],[34.8804418550117,32.0528193460686],[34.8786334639958,32.0466327470143],[34.8605495609931,32.0488218510146],[34.8468438649828,32.0689996810298]]]},"properties":{"Dsc":"תשתית אורתופוטו בישראל עדכני לאפריל 2019","Rms":null,"Ep90":"3","Scale":null,"Source":"MAS_6_ORT_247993-1.0","Resolution":"0.2","SensorType":"OTHER","SourceName":"O_arzi_mz_w84geo_Tiff_20cm","UpdateDate":"06/04/2019"}}]}',
      version: "1.0.0",
      wait_time: 30,
      projection: "roie",
      csv_path: "csv_data/data/wmts_shaziri.csv",
      gridName: "newGrids",
      imageType: ".png",
      layer: "bluemarble-dani-mumhui-Orthophoto",
      users: 15,
      port: 8080,
      CONF_FILE: "/layerSources/locust_configuration.json",
      layer_type: "wmts",
      test_to_run: "Lateron",
      sub_url_for_pycsw: "https://catalog-qa-raster-catalog-pycsw-route-raster.apps.v0h0bdx6.eastus.aroapp.io/",
    }
  env_secret:
    "replace_me"
  env_external_secret:
    {}
  secret_name_api_key_locust: "automation-secret"
  sub_url_secret:
    "automation-sub-url"
  headless: false

image:
  repository: acrarolibotnonprod.azurecr.io/locust-automation
  tag: 2.5.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  # type: NodePort
  annotations: {}

master:
  image: "acrarolibotnonprod.azurecr.io/locust-automation:2.5.3"
  logLevel: INFO
  envs_include_default: true
  env: {}
  args: []
  strategy:
    type: RollingUpdate
  auth:
    enabled: true
    username: "danny"
    password: "danny"
  csv_options:
    enabled: false
    csv: "/home/kaka/dam/"
    csv_history: false
  restartPolicy: Always

worker:
  image: "acrarolibotnonprod.azurecr.io/locust-automation:2.5.3"
  logLevel: INFO
  replicas: 1
  envs_include_default: true
  env: { SUB_URL_FOR_IDS: "https://www.google.com" }
  args: []
  strategy:
    type: RollingUpdate
  restartPolicy: Always

nameOverride: ""
fullnameOverride: ""
pullSecretName: acr-registry

ingress:
  enabled: false
  className: ""
  annotations: {}
  #  kubernetes.io/ingress.class: nginx
  #  kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      pathType: ImplementationSpecific
      path: /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

route:
  enabled: true
  path: /
  https: true
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)

storage:
  pvcName: ingestion-source-pvc
  subPath: ingestion-source